name: Check

on:
    push:
        branches: [main]
    pull_request:
    merge_group:

jobs:
    yarn:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .tool-versions

            - run: yarn
              env:
                  # https://yarnpkg.com/features/security#hardened-mode
                  YARN_ENABLE_HARDENED_MODE: 1

    biome:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .tool-versions

            - run: yarn

            - run: yarn turbo check-biome check-prettier

    eslint:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .tool-versions

            - run: yarn

            - run: yarn turbo check-eslint

    typescript:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .tool-versions

            - run: yarn

            - run: yarn turbo check-svelte check-typescript

    test:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .tool-versions

            - run: yarn

            - run: yarn turbo test
